add_newline = false

[character]
success_symbol = '[INSERT \$](green)'
error_symbol = '[INSERT \$](red)'
vicmd_symbol = '[NORMAL \$](green)'

[git_branch]
symbol = "🌲 "

[hostname]
ssh_only = false

[python]
python_binary = "python3"

[username]
show_always = true
