add_newline = false

[character]
symbol = "INSERT $"
vicmd_symbol = "NORMAL $"

[git_branch]
symbol = "🌲 "

[hostname]
ssh_only = false

[python]
python_binary = "python3"

[username]
show_always = true
